### ISSUE TITLE
updating above v0.22 causes error

### ISSUE THREAD

**Issue by barbalex** [gregjacobs/Autolinker.js#170]
after updating to v0.23 or higher I get:

    Uncaught TypeError: textOrHtml.substring is not a function

It works fine with versions up to v0.22.

I realize this issue may not be reproducible so feel free to close it.

**Comment by gregjacobs** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hmm, maje sure that you provide a string to autolinker.link()
Something like: autolinker.link( myText || '' ); would make sure you aren't accidentally passing undefined or null.
And if you by chance you are passing a number: autolinker.link( String( myNumber ) );

after updating to v0.23 or higher I get:
Uncaught TypeError: textOrHtml.substring is not a function

It works fine with versions up to v0.22.

I realize this issue may not be reproducible so feel free to close it.

**Comment by barbalex** [comment]
thanks, this helps

I am now using:

    autolinker.link(value ? '' + value : '')

which converts null/undefined to '' and numbers to strings.
This runs on v0.27 without error.

**Comment by gregjacobs** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Perfect - that works, and glad to help!



thanks, this helps

I am now using:
autolinker.link(value ? '' + value : '')

which converts null/undefined to '' and numbers to strings.
This runs on v0.27 without error.
